apiVersion: v1
kind: Service
metadata:
  name: mywebsite
  labels:
    app: mywebsite
spec:
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort