apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite
  labels:
    app: mywebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite
        image: ddeepak7794/mywebsite
        ports:
        - containerPort: 80